const Info = [
    // {
    //   image:'https://static01.nyt.com/images/2022/03/30/books/29BOOKEGAN1/29BOOKEGAN1-superJumbo.png?quality=75&auto=webp',
    //   name:'The Candy House',
    //   xname:'The Candy House',
    //   author:'Jennifer Egan',
    //   details:'You don’t need to have read Egan’s Pulitzer-winning “A Visit From the Goon Squad” to jump feet first into this much-anticipated sequel. But for lovers of the 2010 book’s prematurely nostalgic New Yorkers, cerebral beauty and laser-sharp take on modernity, “The Candy House” is like coming home — albeit to dystopia. This time around, Egan’s characters are variously the creators and prisoners of a universe in which, through the wonders of technology, people can access their entire memory banks and use the contents as social media currency. The result is a glorious, hideous fun house that feels more familiar than sci-fi, all rendered with Egan’s signature inventive confidence and — perhaps most impressive of all — heart. “The Candy House” is of its moment, with all that implies.',
    // },
    {
      image:'https://static01.nyt.com/images/2022/12/01/books/01claire-louise-bennett-cover/01claire-louise-bennett-cover-superJumbo.jpg?quality=75&auto=webp',
      name:'Checkout 19',
      xname:'Checkout 19',
      author:'Claire-Louise Bennett',
      details:'Bennett, a British writer who makes her home in Ireland, first leaped onto the scene with her 2015 debut novel, “Pond.” Her second book contains all of the first’s linguistic artistry and dark wit, but it is even more exhilarating. “Checkout 19,” ostensibly the story of a young woman falling in love with language in a working-class town outside London, has an unusual setting: the human mind — a brilliant, surprising, weird and very funny one. All the words one might use to describe this book — experimental, autofictional, surrealist — fail to convey the sheer pleasure of “Checkout 19.” You’ll come away dazed, delighted, reminded of just how much fun reading can be, eager to share it with people in your lives. It’s a love letter to books, and an argument for them, too.',
    },
    {
      image:'https://static01.nyt.com/images/2022/10/09/books/09Kingsolver-cover/09Kingsolver-cover-superJumbo.jpg?quality=75&auto=webp',
      name:'Demon Copperhead',
      xname:'Demon Copperhead',
      author:'Barbara Kingsolver',
      details:'Kingsolver’s powerful new novel, a close retelling of Charles Dickens’s “David Copperfield” set in contemporary Appalachia, gallops through issues including childhood poverty, opioid addiction and rural dispossession even as its larger focus remains squarely on the question of how an artist’s consciousness is formed. Like Dickens, Kingsolver is unblushingly political and works on a sprawling scale, animating her pages with an abundance of charm and the presence of seemingly every creeping thing that has ever crept upon the earth.',
    },
    {
      image:'https://static01.nyt.com/images/2022/09/27/books/27serpell-cover/27serpell-cover-superJumbo.jpg?quality=75&auto=webp',
      name:'The Furrows',
      xname:'The Furrows',
      author:'Namwali Serpell',
      details:'After losing her brother when she was 12, one of the narrators of Serpell’s second novel keeps coming across men who resemble him as she works through her trauma long into adulthood. She enters an intimate relationship with one of them, who’s also haunted by his past. This richly layered book explores the nature of grief, how it can stretch or compress time, reshape memories and make us dream up alternate realities. “I don’t want to tell you what happened,” the narrator says. “I want to tell you how it felt.”',
    },
    {
      image:'https://static01.nyt.com/images/2022/12/03/books/03hernan-diaz-cover/03hernan-diaz-cover-superJumbo.jpg?quality=75&auto=webp',
      name:'Trust',
      xname:'Trust',
      author:'Hernan Diaz',
      details:'Diaz uncovers the secrets of an American fortune in the early 20th century, detailing the dizzying rise of a New York financier and the enigmatic talents of his wife. Each of the novel’s four parts, which are told from different perspectives, redirects the narrative (and upends readers’ expectations) while paying tribute to literary titans from Henry James to Jorge Luis Borges. Whose version of events can we trust? Diaz’s spotlight on stories behind stories seeks out the dark workings behind capitalism, as well as the uncredited figures behind the so-called Great Men of history. It’s an exhilarating pursuit.',
    },
    {
      image:'https://static01.nyt.com/images/2022/06/23/books/review/22BOOKYONG1/22BOOKYONG1-superJumbo.png?quality=75&auto=webp',
      name:'An Immense World',
      xname:'An Immense World: How Animal Senses Reveal the Hidden Realms Around Us',
      author:'Ed Yong',
      details:'Yong certainly gave himself a formidable task with this book — getting humans to step outside their “sensory bubble” and consider how nonhuman animals experience the world. But the enormous difficulty of making sense of senses we do not have is a reminder that each one of us has a purchase on only a sliver of reality. Yong is a terrific storyteller, and there are plenty of surprising animal facts to keep this book moving toward its profound conclusion: The breadth of this immense world should make us recognize how small we really are.',
    },
    {
      image:'https://static01.nyt.com/images/2022/09/28/books/27hsu-cover/27hsu-cover-superJumbo.jpg?quality=75&auto=webp',
      name:'Stay True: A Memoir',
      xname:'Stay True: A Memoir',
      author:'Hua Hsu',
      details:'In this quietly wrenching memoir, Hsu recalls starting out at Berkeley in the mid-1990s as a watchful music snob, fastidiously curating his tastes and mercilessly judging the tastes of others. Then he met Ken, a Japanese American frat boy. Their friendship was intense, but brief. Less than three years later, Ken would be killed in a carjacking. Hsu traces the course of their relationship — one that seemed improbable at first but eventually became a fixture in his life, a trellis along which both young men could stretch and grow.',
    },{
      image:'https://static01.nyt.com/images/2022/09/13/books/13aviv-cover/13aviv-cover-superJumbo.jpg?quality=75&auto=webp',
      name:'Strangers to Ourselves',
      xname:'Strangers to Ourselves: Unsettled Minds and the Stories That Make Us',
      author:'Rachel Aviv',
      details:'In this rich and nuanced book, Aviv writes about people in extreme mental distress, beginning with her own experience of being told she had anorexia when she was 6 years old. That personal history made her especially attuned to how stories can clarify as well as distort what a person is going through. This isn’t an anti-psychiatry book — Aviv is too aware of the specifics of any situation to succumb to anything so sweeping. What she does is hold space for empathy and uncertainty, exploring a multiplicity of stories instead of jumping at the impulse to explain them away.',
    },
    {
      image:'https://static01.nyt.com/images/2022/11/14/books/14linda-villarosa-cover/14linda-villarosa-cover-superJumbo.jpg?quality=75&auto=webp',
      name:'Under the Skin',
      xname:'Under the Skin: The Hidden Toll of Racism on American Lives and on the Health of Our Nation',
      author:'Linda Villarosa',
      details:'Through case histories as well as independent reporting, Villarosa’s remarkable third book elegantly traces the effects of the legacy of slavery — and the doctrine of anti-Blackness that sprang up to philosophically justify it — on Black health: reproductive, environmental, mental and more. Beginning with a long personal history of her awakening to these structural inequalities, the journalist repositions various narratives about race and medicine — the soaring Black maternal mortality rates; the rise of heart disease and hypertension; the oft-repeated dictum that Black people reject psychological therapy — as evidence not of Black inferiority, but of racism in the health care system.',
    },
    {
      image:'https://static01.nyt.com/images/2022/11/15/books/15fintan-o-toole-cover/15fintan-o-toole-cover-superJumbo.jpg?quality=75&auto=webp',
      xname:'We Don’t Know Ourselves',
      name:'We Don’t Know Ourselves',
      author:'Fintan O’Toole',
      details:'O’Toole, a prolific essayist and critic, calls this inventive narrative “a personal history of modern Ireland” — an ambitious project, but one he pulls off with élan. Charting six decades of Irish history against his own life, O’Toole manages to both deftly illustrate a country in drastic flux, and include a sly, self-deprecating biography that infuses his sociology with humor and pathos. You’ll be educated, yes — about increasing secularism, the Celtic tiger, human rights — but you’ll also be wildly, uproariously entertained by a gifted raconteur at the height of his powers.',
    },
  ]
  export default Info;